### ISSUE TITLE
Consider using capsule as a packager?

### ISSUE THREAD

**Issue by linkerlin** [mjanicek/rembulan#11]
[capsule](http://www.capsule.io)
very handy

**Comment by mjanicek** [comment]
A great idea, thank you! This should definitely be more convenient than using Appassembler.

**Comment by mjanicek** [comment]
This has now been done for the standalone REPL and merged into `master`.

I'm not particularly happy with having to name the REPL capsule from command line using

``` sh
mvn package -DstandaloneFinalName=rembulan
```

to get the (executable) capsule in `rembulan-standalone/target/rembulan-capsule.x`, but this will mostly be useful for releases anyway. I think it's sufficient for building from sources, and it seems to work nicely.
